# Generated by Django 5.2 on 2025-04-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('top', 'Top Rated'), ('recommended', 'Recommended'), ('all', 'All')], max_length=20)),
            ],
        ),
    ]
