# Generated by Django 5.2 on 2025-04-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('top', 'Top Rated'), ('recommended', 'Recommended'), ('all', 'All Foods')], max_length=20),
        ),
    ]
